version: '3.7'

services:

  mysql:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9001:9000'
    volumes:
      - ./app:/var/www/php-sphere
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/php-sphere
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge